# General site settings
title: Eli Daniels
description: A collection of my work and projects
url: https://elidaniels99.github.io/Portfolio
baseurl: "" # Leave this empty for GitHub Pages

# GitHub Pages settings
theme: jekyll-theme-hacker 

plugins:
  - jekyll-feed # Include Jekyll plugins as needed

# Navigation
navbar_links:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Projects
    url: /projects

# Jekyll-specific settings
markdown: kramdown
highlighter: rouge

# Build settings
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor", "README.md", "LICENSE"]


# Additional configurations or customizations go here
